services:
  webjoy-dev:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    network_mode: host
    environment:
      - PREACT_APP_ROSBRIDGE_SERVER_HOST=${PREACT_APP_ROSBRIDGE_SERVER_HOST:-slam}