FROM caddy:2.6.2-alpine

WORKDIR /src

COPY Caddyfile.reverse-proxy /etc/caddy/Caddyfile

EXPOSE 8080

ENV ROSBRIDGE_SERVER_HOST=

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]